--- #YAML:1.0
name:               IPC-GimpFu
version:            0.03
abstract:           interface to Gimp's script-fu server
author:
    - Cyril Brulebois <kibi@debian.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Cwd:             0
    IO::Socket::IP:  0
    Proc::Daemon:    0
    Proc::Killall:   0
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
